# Generated by Django 5.2.11 on 2026-03-03 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0003_grade_dia_semana'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.AlterModelTable(
            name='grade',
            table='grade',
        ),
    ]
