# Generated by Django 5.2.11 on 2026-03-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('communication', 'Communication'), ('event', 'Event'), ('observation', 'Observation'), ('pedagogical', 'Pedagogical')], max_length=20, verbose_name='Type')),
                ('date', models.DateField()),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/user')),
                ('class_groups', models.ManyToManyField(blank=True, related_name='messages', to='core.classgroup')),
                ('teachers', models.ManyToManyField(blank=True, related_name='messages', to='core.teacher')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'message',
            },
        ),
    ]
