# Generated by Django 5.2.11 on 2026-03-03 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_componente_curricular_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crianca',
            name='responsaveis',
        ),
        migrations.RemoveField(
            model_name='crianca',
            name='sala',
        ),
        migrations.RemoveField(
            model_name='registro_diario',
            name='crianca',
        ),
        migrations.RemoveField(
            model_name='registro_diario',
            name='cuidador',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='auth_user',
        ),
        migrations.AlterModelTable(
            name='componente_curricular',
            table='componente_curricular',
        ),
        migrations.AlterModelTable(
            name='justificativa',
            table='justificativa',
        ),
        migrations.AlterModelTable(
            name='periodo',
            table='periodo',
        ),
        migrations.AlterModelTable(
            name='professor',
            table='professor',
        ),
        migrations.AlterModelTable(
            name='segmento',
            table='segmento',
        ),
        migrations.AlterModelTable(
            name='turma',
            table='turma',
        ),
    ]
