# Generated by Django 5.2.11 on 2026-03-03 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_crianca_responsaveis_remove_crianca_sala_and_more'),
        ('mensagem', '0002_remove_mensagem_criancas_remove_mensagem_salas_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sala',
        ),
        migrations.DeleteModel(
            name='Crianca',
        ),
        migrations.DeleteModel(
            name='Cuidador',
        ),
        migrations.DeleteModel(
            name='Registro_Diario',
        ),
        migrations.DeleteModel(
            name='Responsavel',
        ),
    ]
