# Generated by Django 5.2.11 on 2026-03-03 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0007_professor_substituto_substituto_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='professor_ausente',
            table='professor_ausente',
        ),
        migrations.AlterModelTable(
            name='professor_substituto',
            table='professor_substituto',
        ),
    ]
