# Generated by Django 5.2.11 on 2026-03-03 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('justification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='core.justification')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='core.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Absence',
                'verbose_name_plural': 'Teacher Absences',
                'db_table': 'teacher_absence',
            },
        ),
        migrations.CreateModel(
            name='TeacherSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('absent_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_needed', to='core.teacher')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_provided', to='core.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Substitution',
                'verbose_name_plural': 'Teacher Substitutions',
                'db_table': 'teacher_substitution',
            },
        ),
    ]
