# Generated by Django 5.2.11 on 2026-03-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_crianca_responsaveis_remove_crianca_sala_and_more'),
        ('mensagem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='criancas',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='salas',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='professores',
            field=models.ManyToManyField(blank=True, to='home.professor'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='turmas',
            field=models.ManyToManyField(blank=True, to='home.turma'),
        ),
        migrations.AlterModelTable(
            name='mensagem',
            table='mensagem',
        ),
    ]
